# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go mod tidy
      - go mod vendor
      - find . -name \*.go -not -path "./vendor/*" -exec goimports -w {} \;
      - mkdir -p executables
      - go build -o executables ./cmd/middleware/...
